name: tz
publish_to: 'none'
version: 1.0.0+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.0
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  flutter_svg: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/temz_logo.jpg
    - assets/temz_logo_clean.svg
