import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:share_plus/share_plus.dart';

const navy = Color(0xFF071B3A);
const blue = Color(0xFF1264E8);
const bg = Color(0xFFF5F8FD);
const green = Color(0xFF159A63);
const red = Color(0xFFD92D4F);
const orange = Color(0xFFE58A00);
const supabaseUrl = 'https://xztnrpfrrqfxqfmboruc.supabase.co';
const supabaseKey = 'sb_publishable_fFB3uYqNtygqBB_ARmKSdQ_qHU5SdTL';
const storePhone = '09012533620';
final db = Supabase.instance.client;
const statuses = ['New Order','Awaiting Agent Acceptance','Accepted','Out for Delivery','Customer Not Available','Unable to Meet Up','Customer Chose Another Day','Delivered','Cancelled'];

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Supabase.initialize(url: supabaseUrl, anonKey: supabaseKey);
  runApp(const TZ());
}

class TZ extends StatelessWidget {
  const TZ({super.key});
  @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner:false,title:'TZ • Temz Store',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:blue)),home:const Gate());
}

class Logo extends StatelessWidget {
  final double size;
  const Logo({super.key,this.size=90});
  @override Widget build(BuildContext context)=>Container(width:size,height:size,padding:const EdgeInsets.all(5),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),boxShadow:const[BoxShadow(color:Colors.black12,blurRadius:12)]),child:Image.asset('assets/temz_logo.jpg',fit:BoxFit.contain));
}

class Gate extends StatelessWidget {
  const Gate({super.key});
  @override Widget build(BuildContext context)=>StreamBuilder<AuthState>(stream:db.auth.onAuthStateChange,builder:(context,snapshot)=>db.auth.currentSession==null?const Login():const ProfileGate());
}

class ProfileGate extends StatefulWidget {
  const ProfileGate({super.key});
  @override State<ProfileGate> createState()=>_ProfileGateState();
}
class _ProfileGateState extends State<ProfileGate>{String? role;String name='';String? error;@override void initState(){super.initState();load();}Future<void> load()async{try{final user=db.auth.currentUser;if(user==null)return;final p=await db.from('profiles').select('role,full_name').eq('id',user.id).maybeSingle();if(p==null)throw Exception('Your account has not been activated by a Temz Store administrator.');if(!mounted)return;setState((){role='${p['role']??'agent'}';name='${p['full_name']??''}';});}catch(e){await db.auth.signOut();if(mounted)setState(()=>error=e.toString().replaceFirst('Exception: ',''));}}@override Widget build(BuildContext context){if(error!=null)return Login(message:error);if(role==null)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Shell(role:role!,name:name);}}

class Login extends StatefulWidget{final String? message;const Login({super.key,this.message});@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final email=TextEditingController();final password=TextEditingController();bool hide=true,busy=false;Future<void> signIn()async{setState(()=>busy=true);try{await db.auth.signInWithPassword(email:email.text.trim().toLowerCase(),password:password.text);}on AuthException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Column(children:[const Logo(size:150),const SizedBox(height:18),const Text('TZ',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900,color:navy)),const Text('TEMZ STORE OPERATIONS',style:TextStyle(letterSpacing:2,color:blue,fontWeight:FontWeight.w800)),if(message!=null)Padding(padding:const EdgeInsets.only(top:16),child:Text(message!,textAlign:TextAlign.center,style:const TextStyle(color:red,fontWeight:FontWeight.w700))),const SizedBox(height:26),Card(child:Padding(padding:const EdgeInsets.all(22),child:Column(children:[TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email',prefixIcon:Icon(Icons.mail_outline))),const SizedBox(height:14),TextField(controller:password,obscureText:hide,decoration:InputDecoration(labelText:'Password',prefixIcon:const Icon(Icons.lock_outline),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)))),const SizedBox(height:20),SizedBox(width:double.infinity,height:52,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:navy),onPressed:busy?null:signIn,child:busy?const CircularProgressIndicator(color:Colors.white):const Text('SIGN IN'))),const SizedBox(height:12),const Text('Temz Store • 09012533620',style:TextStyle(color:Colors.grey))])))])))));
}

class Shell extends StatefulWidget{final String role,name;const Shell({super.key,required this.role,required this.name});@override State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{int tab=0;final titles=const['Dashboard','Orders','Agents','Stock','Receipts','Settings'];@override Widget build(BuildContext context){final pages=<Widget>[Dashboard(role:role),Orders(role:role),Agents(role:role),Stock(role:role),const Receipts(),Settings(role:role)];return Scaffold(appBar:AppBar(title:Text(titles[tab],style:const TextStyle(fontWeight:FontWeight.w900,color:navy)),actions:const[Padding(padding:EdgeInsets.only(right:12),child:Logo(size:42))]),drawer:Drawer(child:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Center(child:Logo(size:95)),const Center(child:Text('TEMZ STORE',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900,color:navy))),Center(child:Text(role.toUpperCase(),style:const TextStyle(color:blue,fontWeight:FontWeight.w800))),const Divider(height:30),for(int i=0;i<titles.length;i++)ListTile(selected:i==tab,leading:Icon([Icons.grid_view,Icons.receipt_long,Icons.groups,Icons.inventory_2,Icons.request_quote,Icons.settings][i]),title:Text(titles[i]),onTap:(){setState(()=>tab=i);Navigator.pop(context);}),const Divider(),ListTile(leading:const Icon(Icons.logout),title:const Text('Log out'),onTap:()=>db.auth.signOut())])),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.grid_view),label:'Home'),NavigationDestination(icon:Icon(Icons.receipt_long),label:'Orders'),NavigationDestination(icon:Icon(Icons.groups),label:'Agents'),NavigationDestination(icon:Icon(Icons.inventory_2),label:'Stock'),NavigationDestination(icon:Icon(Icons.request_quote),label:'Receipts'),NavigationDestination(icon:Icon(Icons.settings),label:'Settings')]));}}

Future<List<Map<String,dynamic>>> getOrders(String role)async{var q=db.from('orders').select('id,order_number,created_at,customer_name,customer_phone,customer_email,state,city,delivery_address,assigned_agent_id,status,scheduled_delivery_date,total_amount,amount_charged,amount_remitted,extra_charge,extra_charge_reason,payment_method,receipt_generated');if(role=='agent')q=q.eq('assigned_agent_id',db.auth.currentUser!.id);final rows=await q.order('created_at',ascending:false);return List<Map<String,dynamic>>.from(rows);}
Future<List<Map<String,dynamic>>> getItems(String id)async{final rows=await db.from('order_items').select('quantity,unit_price,products(name)').eq('order_id',id);return List<Map<String,dynamic>>.from(rows);}

class Dashboard extends StatefulWidget{final String role;const Dashboard({super.key,required this.role});@override State<Dashboard> createState()=>_DashboardState();}
class _DashboardState extends State<Dashboard>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=getOrders(widget.role);}int n(List<Map<String,dynamic>> x,String s)=>x.where((o)=>o['status']==s).length;@override Widget build(BuildContext context)=>FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('Dashboard error: ${s.error}'));final x=s.data??[];final rem=x.where((o)=>o['status']=='Delivered'&&(num.tryParse('${o['amount_remitted']??0}')??0)<(num.tryParse('${o['amount_charged']??0}')??0)).length;return RefreshIndicator(onRefresh:()async{setState(()=>future=getOrders(widget.role));await future;},child:ListView(padding:const EdgeInsets.all(16),children:[Text(widget.role=='admin'?'Good day, Admin':'Agent dashboard',style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900,color:navy)),const SizedBox(height:20),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.45,children:[Stat('New Orders',n(x,'New Order'),blue),Stat('Awaiting Acceptance',n(x,'Awaiting Agent Acceptance'),orange),Stat('Out for Delivery',n(x,'Out for Delivery'),navy),Stat('Delivered',n(x,'Delivered'),green),Stat('Postponed',n(x,'Customer Chose Another Day'),orange),Stat('Cancelled',n(x,'Cancelled'),red),Stat('Awaiting Remittance',rem,Colors.purple)]),const SizedBox(height:22),const Text('Recent orders',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900,color:navy)),...x.take(8).map((o)=>Card(child:ListTile(title:Text('${o['order_number']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${o['customer_name']} • ${o['status']}'),trailing:Text('₦${o['total_amount']}'))))]));});}
class Stat extends StatelessWidget{final String title;final int value;final Color color;const Stat(this.title,this.value,this.color,{super.key});@override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Icon(Icons.circle,color:color,size:15),Text('$value',style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900,color:navy)),Text(title,style:TextStyle(fontSize:11,color:Colors.grey.shade700,fontWeight:FontWeight.w700))])));}

class Orders extends StatefulWidget{final String role;const Orders({super.key,required this.role});@override State<Orders> createState()=>_OrdersState();}
class _OrdersState extends State<Orders>{String filter='All',search='';late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=getOrders(widget.role);}void reload()=>setState(()=>future=getOrders(widget.role));@override Widget build(BuildContext context)=>FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('Orders error: ${s.error}'));final rows=(s.data??[]).where((o){final t='${o['order_number']} ${o['customer_name']} ${o['customer_phone']}'.toLowerCase();return(filter=='All'||o['status']==filter)&&t.contains(search.toLowerCase());}).toList();return Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,8,16,6),child:TextField(onChanged:(v)=>setState(()=>search=v),decoration:const InputDecoration(hintText:'Search order, customer or phone',prefixIcon:Icon(Icons.search)))),SizedBox(height:46,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:14),children:['All',...statuses].map((s)=>Padding(padding:const EdgeInsets.only(right:6),child:ChoiceChip(label:Text(s,style:const TextStyle(fontSize:10)),selected:filter==s,onSelected:(_)=>setState(()=>filter=s)))).toList())),Expanded(child:RefreshIndicator(onRefresh:()async{reload();await future;},child:ListView(padding:const EdgeInsets.all(14),children:rows.map((o)=>Card(child:ListTile(onTap:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderDetail(order:o,role:widget.role)));reload();},leading:StatusIcon('${o['status']}'),title:Text('${o['order_number']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${o['customer_name']}\n${o['city']}, ${o['state']}'),isThreeLine:true))).toList())))]) ;});}
class StatusIcon extends StatelessWidget{final String status;const StatusIcon(this.status,{super.key});@override Widget build(BuildContext context){final c=status=='Delivered'?green:status=='Cancelled'?red:(status.contains('Not')||status.contains('Unable')||status.contains('Another')?orange:blue);return CircleAvatar(backgroundColor:c.withOpacity(.1),child:Icon(status=='Delivered'?Icons.check:Icons.local_shipping_outlined,color:c));}}

class OrderDetail extends StatefulWidget{final Map<String,dynamic> order;final String role;const OrderDetail({super.key,required this.order,required this.role});@override State<OrderDetail> createState()=>_OrderDetailState();}
class _OrderDetailState extends State<OrderDetail>{late Map<String,dynamic> o;List<Map<String,dynamic>> items=[];bool loading=true;@override void initState(){super.initState();o=Map<String,dynamic>.from(widget.order);load();}Future<void> load()async{items=await getItems('${o['id']}');if(mounted)setState(()=>loading=false);}Future<void> refreshOrder()async{final r=await db.from('orders').select().eq('id',o['id']).single();o=Map<String,dynamic>.from(r);await load();}Future<void> openUrl(String value)async{final u=Uri.parse(value);if(await canLaunchUrl(u))await launchUrl(u,mode:LaunchMode.externalApplication);}Future<void> action(String status)async{try{await db.rpc('tz_agent_update_order',params:{'p_order':o['id'],'p_status':status,'p_scheduled_date':null});await refreshOrder();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}Future<void> assign()async{final agents=await db.from('profiles').select('id,full_name,state').eq('role','agent').eq('available',true);if(!mounted)return;showModalBottomSheet(context:context,builder:(_)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Assign available agent',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:navy)),for(final a in agents)ListTile(title:Text('${a['full_name']??''}'),subtitle:Text('${a['state']??''}'),onTap:()async{await db.rpc('tz_assign_order',params:{'p_order':o['id'],'p_agent':a['id']});if(mounted)Navigator.pop(context);await refreshOrder();})]));}
Future<void> delivered()async{final charged=TextEditingController(text:'${o['total_amount']??0}');final remitted=TextEditingController(text:'0');String payment='Cash';final ok=await showDialog<bool>(context:context,builder:(_)=>StatefulBuilder(builder:(context,setDialog)=>AlertDialog(title:const Text('Confirm delivery'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:charged,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount charged')),TextField(controller:remitted,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount remitted')),DropdownButtonFormField<String>(value:payment,items:const[DropdownMenuItem(value:'Cash',child:Text('Cash')),DropdownMenuItem(value:'Bank Transfer',child:Text('Bank Transfer'))],onChanged:(v)=>setDialog(()=>payment=v??'Cash'),decoration:const InputDecoration(labelText:'Payment method'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Confirm'))])));if(ok!=true)return;try{await db.rpc('tz_agent_update_order',params:{'p_order':o['id'],'p_status':'Delivered','p_scheduled_date':null,'p_amount_charged':num.tryParse(charged.text)??0,'p_amount_remitted':num.tryParse(remitted.text)??0,'p_payment_method':payment});await refreshOrder();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
@override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final phone='${o['customer_phone']??''}';final wa=phone.replaceFirst(RegExp(r'^0'),'');final address='${o['delivery_address']??''}, ${o['city']??''}, ${o['state']??''} Nigeria';return Scaffold(appBar:AppBar(title:Text('${o['order_number']}')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${o['customer_name']??''}',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:navy)),Text(phone),Text(address),Chip(label:Text('${o['status']}'))]))),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Products',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900,color:navy)),for(final i in items)ListTile(contentPadding:EdgeInsets.zero,title:Text('${(i['products'] as Map?)?['name']??'Product'}'),trailing:Text('× ${i['quantity']}')),const Divider(),Text('TOTAL: ₦${o['total_amount']??0}',style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:navy))])),Card(child:Padding(padding:const EdgeInsets.all(18),child:Wrap(spacing:8,runSpacing:8,children:[FilledButton.tonal(onPressed:()=>openUrl('tel:$phone'),child:const Text('Call')),FilledButton.tonal(onPressed:()=>openUrl('https://wa.me/234$wa'),child:const Text('WhatsApp')),FilledButton.tonal(onPressed:()=>openUrl('https://www.google.com/maps/search/?api=1&query=${Uri.encodeComponent(address)}'),child:const Text('Navigate')),if(widget.role=='admin'&&o['assigned_agent_id']==null)FilledButton(onPressed:assign,child:const Text('Assign Agent')),if(widget.role=='agent'&&o['status']=='Awaiting Agent Acceptance')... [FilledButton(onPressed:()=>action('Accepted'),child:const Text('Accept')),FilledButton.tonal(onPressed:()=>action('Cancelled'),child:const Text('Reject'))],if(widget.role=='agent'&&(o['status']=='Accepted'||o['status']=='Customer Chose Another Day'))FilledButton(onPressed:()=>action('Out for Delivery'),child:const Text('Out for Delivery')),if(widget.role=='agent'&&o['status']=='Out for Delivery')... [FilledButton(onPressed:delivered,child:const Text('Delivered')),FilledButton.tonal(onPressed:()=>action('Customer Not Available'),child:const Text('Not Available')),FilledButton.tonal(onPressed:()=>action('Unable to Meet Up'),child:const Text('Unable to Meet Up')),FilledButton.tonal(onPressed:()=>action('Cancelled'),child:const Text('Cancelled'))],if(o['status']=='Delivered')FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>Receipt(order:o,items:items))),child:const Text('Generate Receipt'))]))]);}}

class Agents extends StatefulWidget{final String role;const Agents({super.key,required this.role});@override State<Agents> createState()=>_AgentsState();}
class _AgentsState extends State<Agents>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=load();}Future<List<Map<String,dynamic>>> load()async{final r=await db.from('profiles').select('id,full_name,email,phone,state,available').eq('role','agent').order('full_name');return List<Map<String,dynamic>>.from(r);}@override Widget build(BuildContext context)=>FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(16),children:[Text('Agents (${s.data!.length})',style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900,color:navy)),for(final a in s.data!)Card(child:SwitchListTile(value:a['available']==true,onChanged:role=='admin'?(v)async{await db.from('profiles').update({'available':v}).eq('id',a['id']);setState(()=>future=load());}:null,title:Text('${a['full_name']??''}'),subtitle:Text('${a['phone']??''} • ${a['state']??''}'),secondary:const Icon(Icons.person_outline,color:blue))) ]);});}

class Stock extends StatefulWidget{final String role;const Stock({super.key,required this.role});@override State<Stock> createState()=>_StockState();}
class _StockState extends State<Stock>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=load();}Future<List<Map<String,dynamic>>> load()async{final r=await db.from('products').select('id,name,selling_price,central_stock,active').order('name');return List<Map<String,dynamic>>.from(r);}@override Widget build(BuildContext context)=>FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(16),children:[const Text('Central Stock',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900,color:navy)),for(final p in s.data!)Card(child:ListTile(leading:const Icon(Icons.inventory_2_outlined,color:blue),title:Text('${p['name']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('₦${p['selling_price']}'),trailing:Text('${p['central_stock']}',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:navy))))]);});}

class Receipts extends StatefulWidget{const Receipts({super.key});@override State<Receipts> createState()=>_ReceiptsState();}
class _ReceiptsState extends State<Receipts>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=load();}Future<List<Map<String,dynamic>>> load()async{final r=await db.from('orders').select('id,order_number,customer_name,customer_phone,delivery_address,city,state,total_amount,payment_method,receipt_generated').eq('status','Delivered').order('created_at',ascending:false);return List<Map<String,dynamic>>.from(r);}@override Widget build(BuildContext context)=>FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(16),children:[const Text('Customer Receipts',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900,color:navy)),for(final o in s.data!)Card(child:ListTile(leading:const Icon(Icons.verified,color:green),title:Text('${o['order_number']}'),subtitle:Text('${o['customer_name']} • ${o['payment_method']??''}'),trailing:IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>Receipt(order:o,items:const[]))),icon:const Icon(Icons.open_in_new))))]);});}

class Receipt extends StatelessWidget{final Map<String,dynamic> order;final List<Map<String,dynamic>> items;const Receipt({super.key,required this.order,required this.items});@override Widget build(BuildContext context){final address='${order['delivery_address']??''}, ${order['city']??''}, ${order['state']??''}';return Scaffold(appBar:AppBar(title:const Text('Customer Receipt')),body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(18),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[const Logo(size:105),const Text('TEMZ STORE',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:navy)),const Text(storePhone,style:TextStyle(color:blue,fontWeight:FontWeight.w700)),const Divider(height:30),const Text('CUSTOMER RECEIPT',style:TextStyle(letterSpacing:2,fontWeight:FontWeight.w900)),const SizedBox(height:12),RowItem('TZ Order No.','${order['order_number']}'),RowItem('Customer','${order['customer_name']}'),RowItem('Phone','${order['customer_phone']}'),RowItem('Address',address),for(final i in items)RowItem('${(i['products'] as Map?)?['name']??'Product'} × ${i['quantity']}',''),const Divider(),RowItem('TOTAL PAID','₦${order['total_amount']}'),RowItem('Payment Method','${order['payment_method']??'Cash'}'),const SizedBox(height:18),Container(padding:const EdgeInsets.symmetric(horizontal:28,vertical:10),decoration:BoxDecoration(border:Border.all(color:green,width:3),borderRadius:BorderRadius.circular(10)),child:const Text('PAID',style:TextStyle(color:green,fontSize:28,fontWeight:FontWeight.w900,letterSpacing:4))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>Share.share('TEMZ STORE\nOrder: ${order['order_number']}\nCustomer: ${order['customer_name']}\nTOTAL PAID: ₦${order['total_amount']}\nPayment: ${order['payment_method']??'Cash'}'),icon:const Icon(Icons.share),label:const Text('Share Receipt'))])))))));}}
class RowItem extends StatelessWidget{final String label,value;const RowItem(this.label,this.value,{super.key});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Text(label,style:const TextStyle(fontWeight:FontWeight.w700))),Expanded(child:Text(value,textAlign:TextAlign.right))]));}

class Settings extends StatelessWidget{final String role;const Settings({super.key,required this.role});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Logo(size:110),const Center(child:Text('TEMZ STORE',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:navy))),const SizedBox(height:20),Card(child:ListTile(leading:const Icon(Icons.business,color:blue),title:const Text('Business'),subtitle:Text('Temz Store • $storePhone'))),Card(child:ListTile(leading:const Icon(Icons.security,color:blue),title:const Text('Account role'),subtitle:Text(role.toUpperCase()))),Card(child:ListTile(leading:const Icon(Icons.logout,color:red),title:const Text('Log out'),onTap:()=>db.auth.signOut()))]);}
